services:
  trivia-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: igalbelov/trivia-game:v1.0
    container_name: trivia_game
    stdin_open: true # שומר על ערוץ קלט פתוח
    tty: true        # מקצה טרמינל וירטואלי (מונע קריסה של המשחק)
    restart: always
    ports:
      - "8000:8000"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - trivia-app
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/dashboards:/var/lib/grafana/dashboards
      - ./monitoring/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge