services:
  # השם כאן חייב להיות זהה למה שמופיע ב-depends_on
  trivia-app: 
    build: .
    image: trivia-game:latest
    container_name: trivia_game
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    # כאן היה ה-ERROR: השם חייב להיות trivia-app (שם השירות)
    depends_on:
      - trivia-app
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      # אנחנו אומרים לדוקר: קח את מה שיש בתיקיית המוניטורינג אצלי, ושים אותו בתיקיית ההגדרות של גרפאנה
      - ./monitoring/dashboards:/var/lib/grafana/dashboards
      - ./monitoring/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge